name: CensorshipDissent
channels:
  - conda-forge
dependencies:
  - python=3.12.*
  - numpy=1.26.*
  - scipy=1.13.*
  - matplotlib=3.8.*
  - cmcrameri=1.9.*
  - tqdm=4.66.*
  - networkx=3.3.*
  - graphviz=9.0.*
  - pygraphviz=1.13.*
